### ISSUE TITLE
GA Instructor Review Recommended

### ISSUE THREAD

**Issue by danwilhelm** [generalassembly-studio/python-programming-101-cwe-materials#3]
An experienced GA instructor should comprehensively review these materials. In their current form, I believe they will be confusing to students and are not representative of GA quality.

Some potential issues include:
- Numerous typos and non-standard spellings ("programme" instead of "program")
- Explanations are often awkwardly worded (e.g. 'for loop' slides) or completely missing (e.g. the data type slides)
- Concepts often do not build on each other, forcing the instructor to explain or invent a narrative
- Code is sometimes inconsistently written (see PEP 8 -- the official Python style guide)

Finally, the coding exercises in 'code/' have nothing to do with what was taught in the slide deck. Students taking this workshop have significant trouble with basic programming constructs, such as for loops and functions. In my opinion, it is inappropriate to have the in-class exercises cover an intermediate-level programming library (Pandas). Instead, they should reinforce what is taught in class -- for loops, functions, and built-in data types.

**Comment by jeff-boykin** [comment]
Thanks @danwilhelm! Great feedback here. I'll put these materials through another round of copyedits to fix typos and standardize (Americanize) spelling, as our SME was from London. I'd be happy to chat in-person sometime to get your feedback on these other issues. Do you typically teach from our downtown or Santa Monica locations?

**Comment by danwilhelm** [comment]
Hi @jeff-boykin, I have been teaching with GA continuously for over two years. Currently, I teach a number of data science, SQL, and Python workshops at both LA locations. I could chat later this week, let me know when is good for you -- dan@danwilhelm.com.

**Comment by jeff-boykin** [comment]
Thanks @danwilhelm. I just put the deck and lesson readme through another round of copyedits. Materials were actually created by an experienced GA instructor, but I agree that it always helps to have a second set of eyes.

In terms of use cases, the audiences do tend to be novice programmers but we've also seen requests for elements that review python for existing programmers, so we tried to strike a balance.

However, I'd be happy follow up about your content-specific suggestions (e.g. Python code inconsistencies, etc) and in general chat about your experiences as an instructor. I am working out of our Santa Monica office and will follow up via email.
