### ISSUE TITLE
Upgrade to Python 3?

### ISSUE THREAD

**Issue by jeff-boykin** [generalassembly-studio/python-programming-101-cwe-materials#5]
Suggestion by specific audience stakeholders to upgrade code walkthrough to Python 3.5.x. 

Note: Originally preferred Python 2.7 in order to align with enterprise stable release used in data science campus courses.

**Comment by Protosac** [comment]
I think its a great idea. Beginners these days should really get their intro with Python 3. I was thinking of submitting a PR for it and came here to see if this was already underway :)

**Comment by jeff-boykin** [comment]
@Protosac Right, that makes sense. If you have a modified version with updated code, feel free to submit a PR!
